version: "3.9"

volumes:
  note-mark_data:
  db_data:

services:
  note-mark:
    image: navystack/mark-note:latest
    restart: unless-stopped
    volumes:
      - note-mark_data:/app/data
    environment:
      JWT_SECRET: ${JWT_SECRET:?jwt secret required}
      CORS_ORIGINS: "http://localhost:8000"
      DB__TYPE: postgres
      DB__URI: "host=${DB_HOST:-postgres} user=${PG_USER:-notemark} password=${PG_PASS} dbname=${PG_DB:-notemark} port=${PG_PORT:-5432} sslmode=${PG_SSL:-disable} TimeZone=${TIME_ZONE:-UTC}"
    ports:
      - 8000:8000
    env_file:
      - .env

  postgres:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${PG_DB} -U $${PG_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${PG_DB:-notemark}
      POSTGRES_USER: ${PG_USER:-notemark}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env